/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author Fermin Covarrubias Ramos - 4k - 20110309
 */
public class PrincipalVentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVentanaLogin
     */
    public PrincipalVentanaLogin() {
        initComponents();
        
       

    }
        public static String email="";
        public static String contraseña="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoEmpresa = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        separadorBienvenidoYDatos = new javax.swing.JSeparator();
        introduzcatexto = new javax.swing.JLabel();
        EmailTexto = new javax.swing.JLabel();
        espacioemail = new javax.swing.JTextField();
        ContrasenaTexto = new javax.swing.JLabel();
        espaciocontra = new javax.swing.JPasswordField();
        SiguienteBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Bienvenido al Servicio a Cliente de Carls Jr.! [BETA]");

        LogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/fotos/OkOMoafq_400x400.png"))); // NOI18N

        bienvenida.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        bienvenida.setText("Bienvenido al Servicio a Domicilio");

        separadorBienvenidoYDatos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        introduzcatexto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        introduzcatexto.setText("Introduzca sus datos");

        EmailTexto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        EmailTexto.setText("Email/Numero Celular:");

        espacioemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                espacioemailKeyTyped(evt);
            }
        });

        ContrasenaTexto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        ContrasenaTexto.setText("Contraseña:");

        espaciocontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                espaciocontraKeyTyped(evt);
            }
        });

        SiguienteBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SiguienteBoton.setText("Siguiente");
        SiguienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LogoEmpresa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(introduzcatexto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separadorBienvenidoYDatos)
                            .addComponent(EmailTexto)
                            .addComponent(espacioemail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ContrasenaTexto)
                            .addComponent(espaciocontra))
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SiguienteBoton)
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoEmpresa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(separadorBienvenidoYDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introduzcatexto)
                        .addGap(48, 48, 48)
                        .addComponent(EmailTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(espacioemail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ContrasenaTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(espaciocontra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(SiguienteBoton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espacioemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_espacioemailKeyTyped
        
        System.out.println("Introduciendo datos en casilla Email");
        
    }//GEN-LAST:event_espacioemailKeyTyped

    private void espaciocontraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_espaciocontraKeyTyped
        
        System.out.println("Introduciendo datos en contraseña");
        
    }//GEN-LAST:event_espaciocontraKeyTyped

    private void SiguienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteBotonActionPerformed
        
        System.out.println("Presionaste en Siguiente");
        email=espacioemail.getText();
        contraseña=espaciocontra.getText();
        Pedidos pds = new Pedidos();
        pds.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_SiguienteBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContrasenaTexto;
    private javax.swing.JLabel EmailTexto;
    private javax.swing.JLabel LogoEmpresa;
    private javax.swing.JButton SiguienteBoton;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JPasswordField espaciocontra;
    private javax.swing.JTextField espacioemail;
    private javax.swing.JLabel introduzcatexto;
    private javax.swing.JSeparator separadorBienvenidoYDatos;
    // End of variables declaration//GEN-END:variables
}
